site_name: Brev Dev Docs
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css
  - stylesheets/style.css
  - stylesheets/highlight.css
  - stylesheets/custom.scss
copyright: brev.dev 2021 -- All rights reserved
extra:
  copyright: Brev 2021
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/brevdev
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/brevdev
    - icon: fontawesome/brands/discord
      link: https://discord.gg/NVDyv7TUgJ

nav:
  # - Home: index.md
  # - Tutorials:
  #     - Home: tutorials/index.md
  #     - Tutorial 1: tutorials/automatically-set-up.md
  - How-Tos:
      - Home: howto/index.md
      - Copy Personal Settings: howto/copy-personal-settings.md
      - Common Installations: howto/automatically-set-up.md
      - Find Your Localhost: howto/find-my-localhost.md
      - Make a Port Public: howto/make-port-public.md
      - Environment Variables: howto/env-vars-dot-brev.md
      - Troubleshoot Reset: howto/troubleshoot-reset.md
      - Encrypted Secrets: howto/secret-variables.md
      - Create an Organization: howto/create-org.md
      - Configure SSH Proxy Daemon at Boot: howto/configure-ssh-proxy-daemon-at-boot.md
      - Connect Via Emacs: howto/connect-via-emacs.md
      - Connect Via VSCode: howto/connect-via-vscode.md
      - Connect Via Jetbrains: howto/connect-via-jetbrains.md
      - Invite Users: howto/invite-users-to-org.md
      # - Share Your Workspace: howto/share-your-workspace.md
  - Reference:
      - Home: reference/index.md
      - Setup Scripts (.brev): reference/dot-brev-setup-script.md
      - CLI Docs: reference/brev-cli.md
      - Debugging: reference/debugging.md
  # - Discussions:
  #     - Home: discussions/index.md
  #     - Brev DB Best Practices: discussions/best-practices-for-brev-database.md
  #     - Our 2 Principles: discussions/our-two-principles.md
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - python
    - bash
  logo: icon.png
  favicon: favicon.png
  custom_dir: overrides
  # palette:
  #   primary: deep orange
  #   accent: cyan
  font:
    text: Red Hat Text
    code: Space Mono
  features:
    - navigation.expand
    - content.tabs.link

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences
  - attr_list
