site_name: Brev Dev Docs
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css
  - stylesheets/style.css
  - stylesheets/highlight.css
  - stylesheets/custom.scss
copyright: brev.dev 2021 -- All rights reserved
extra:
  copyright: Brev 2021
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/brevdev
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/brevdev
    - icon: fontawesome/brands/discord
      link: https://discord.gg/NVDyv7TUgJ

nav:
  # - Home: index.md
  # - Tutorials:
  #     - Home: tutorials/index.md
  #     - Tutorial 1: tutorials/automatically-set-up.md
  - How-Tos:
      - Home: howto/index.md
      - Common Installations: howto/automatically-set-up.md
      - Remotely Access a Workspace's localhost Without Making In Public: howto/access-workspace-localhost.md
      - Make a Port Public: howto/make-port-public.md
      - Environment Variables: howto/env-vars-dot-brev.md
      - Troubleshoot Reset: howto/troubleshoot-reset.md
      - Encrypted Secrets: howto/secret-variables.md
      - Create an Organization: howto/create-org.md
      - Invite Users to Your Organization: howto/invite-users-to-org.md
      - Configure Brev Daemons: howto/configure-brev-daemons.md
      - Connect Via SSH: howto/connect-via-ssh.md
      - Connect Via Emacs: howto/connect-via-emacs.md
      - Connect Via VSCode: howto/connect-via-vscode.md
      - Connect Via Jetbrains: howto/connect-via-jetbrains.md
  - Reference:
      - Home: reference/index.md
      - Setup Scripts (.brev): reference/dot-brev-setup-script.md
      - CLI Docs: reference/brev-cli.md
      - Debugging: reference/debugging.md
      - Workspace to Workspace Networking: reference/p2p-workspace-networking.md
  # - Discussions:
  #     - Home: discussions/index.md
  #     - Brev DB Best Practices: discussions/best-practices-for-brev-database.md
  #     - Our 2 Principles: discussions/our-two-principles.md
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - python
    - bash
  logo: icon.png
  favicon: favicon.png
  custom_dir: overrides
  # palette:
  #   primary: deep orange
  #   accent: cyan
  font:
    text: Red Hat Text
    code: Space Mono

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences
  - attr_list
